name: publish-web-jar

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional tag (starts with `web-`). Default to the tag of the selected branch.'
        required: false
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Get version
        id: version
        run: echo "VERSION=$(./gradlew -q :web:printVersion)" >> "$GITHUB_OUTPUT"
      - name: Validate tag format and version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ ! -z "${{ github.event.inputs.tag }}" ]; then
            TAG=${{ github.event.inputs.tag }}
          else
            TAG=${GITHUB_REF#refs/tags/}
          fi
          if [[ ! $TAG =~ ^web- ]]; then
            echo "Error: Tag must start with 'web-'"
            exit 1
          fi
          if [[ ! $TAG == web-${{ steps.version.outputs.VERSION }} ]]; then
            echo "Error: Tag version ($TAG) does not match project version (web-${{ steps.version.outputs.VERSION }})"
            exit 1
          fi
      - name: Install Node modules
        run: npm install
      - name: Build a publishable JAR
        run: ./gradlew clean :web:publish
        env:
          APTABASE_ID: ${{ secrets.APTABASE_ID }}
      - name: Publish to Sonatype
        run: ./gradlew :web:jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
          CI: true
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
