name: publish-jar

on:
  workflow_dispatch:
    inputs: { }

permissions:
  contents: read

jobs:
  publish-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Validate ref type
        run: |
          if [[ ! $GITHUB_REF == refs/tags/* ]]; then
            echo "Error: This workflow can only be triggered for tags"
            exit 1
          fi
      - name: Get version
        id: version
        run: echo "VERSION=$(./gradlew -q printVersion)" >> "$GITHUB_OUTPUT"
      - name: Validate tag format and version
        run: |
          if [[ ! ${{ github.ref_name }} =~ ^v ]]; then
            echo "Error: Tag must start with 'v'"
            exit 1
          fi
          if [[ ! ${{ github.ref_name }} == v${{ steps.version.outputs.VERSION }} ]]; then
            echo "Error: Tag version (${{ github.ref_name }}) does not match project version (v${{ steps.version.outputs.VERSION }})"
            exit 1
          fi
      - name: Install Node modules
        run: npm install
      - name: Compile tailwindcss
        run: ./node_modules/.bin/postcss ./frontend/stylesheets/tailwindbase.css --config . --output ./src/main/resources/assets/stylesheets/tailwindbase.css
      - name: Compile Svelte
        run: ENABLE_SVELTE_CHECK=true ./node_modules/webpack/bin/webpack.js --config ./webpack.config.js --output-path ./src/main/resources/assets --mode production
      - name: Build a publishable JAR
        run: ./gradlew publish
      - name: Publish to Sonatype
        run: ./gradlew jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
          CI: true
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
