name: publish-jar

on:
  workflow_dispatch:
    inputs: { }

permissions:
  contents: read

jobs:
  publish-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: 'stable'
          install-chromedriver: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
      - name: Install Node modules
        run: npm install
      - name: Compile tailwindcss
        run: ./node_modules/.bin/postcss ./frontend/stylesheets/tailwindbase.css --config . --output ./src/main/resources/assets/stylesheets/tailwindbase.css
      - name: Compile Svelte
        run: ENABLE_SVELTE_CHECK=true ./node_modules/webpack/bin/webpack.js --config ./webpack.config.js --output-path ./src/main/resources/assets --mode production
      - name: Build a publishable JAR
        run: ./gradlew publish
      - name: Publish to Sonatyp
        run: ./gradlew jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
